import'dotenv/config';import http from'node:http';import express from'express';import helmet from'helmet';import cors from'cors';import jwt from'jsonwebtoken';import bcrypt from'bcryptjs';import{WebSocketServer}from'ws';import{readFile}from'node:fs/promises';import{pool}from'./db.js';
if(!process.env.DATABASE_URL)throw new Error('DATABASE_URL fehlt.');if(!process.env.JWT_SECRET)throw new Error('JWT_SECRET fehlt.');
await pool.query(await readFile(new URL('../sql/001_init.sql',import.meta.url),'utf8'));
const admins=Number((await pool.query("SELECT COUNT(*) c FROM users WHERE role='admin'")).rows[0].c);if(!admins&&process.env.ADMIN_PASSWORD){const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD,12);await pool.query("INSERT INTO users(username,password_hash,role,active) VALUES($1,$2,'admin',TRUE) ON CONFLICT(username) DO NOTHING",[process.env.ADMIN_USERNAME||'admin',hash]);}
const app=express();app.use(helmet({contentSecurityPolicy:false,crossOriginEmbedderPolicy:false}));app.use(cors({origin:process.env.CORS_ORIGIN==='*'?true:process.env.CORS_ORIGIN?.split(',')||true}));app.use(express.json({limit:'12mb'}));app.use(express.static(new URL('../public',import.meta.url).pathname));
const sign=u=>jwt.sign({sub:u.id,username:u.username,role:u.role},process.env.JWT_SECRET,{expiresIn:'12h'});function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace(/^Bearer /,''),process.env.JWT_SECRET);next()}catch{res.status(401).json({error:'Anmeldung erforderlich'})}}const role=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'Keine Berechtigung'});const audit=(uid,action,entity,details={})=>pool.query('INSERT INTO audit_log(user_id,action,entity,details) VALUES($1,$2,$3,$4)',[uid,action,entity,details]);
app.get('/api/health',async(_q,r)=>{await pool.query('SELECT 1');r.json({ok:true,version:'0.85-online'})});
app.post('/api/auth/login',async(req,res)=>{const q=await pool.query('SELECT * FROM users WHERE lower(username)=lower($1) AND active=TRUE',[String(req.body?.username||'').trim()]),u=q.rows[0];if(!u||!await bcrypt.compare(String(req.body?.password||''),u.password_hash))return res.status(401).json({error:'Benutzername oder Passwort ist falsch.'});await audit(u.id,'login','auth');res.json({token:sign(u),user:{id:u.id,username:u.username,role:u.role}})});
app.get('/api/auth/me',auth,(q,r)=>r.json({user:q.user}));app.get('/api/state',auth,async(_q,r)=>{const x=await pool.query('SELECT state_key,payload,revision,updated_at FROM app_state');r.json(Object.fromEntries(x.rows.map(v=>[v.state_key,{payload:v.payload,revision:Number(v.revision),updatedAt:v.updated_at}])))});
let broadcast=()=>{};app.put('/api/state/:key',auth,role('admin','editor'),async(req,res)=>{const key=String(req.params.key).slice(0,100),payload=req.body?.payload??req.body??{};const q=await pool.query('INSERT INTO app_state(state_key,payload,revision,updated_by,updated_at) VALUES($1,$2,1,$3,NOW()) ON CONFLICT(state_key) DO UPDATE SET payload=EXCLUDED.payload,revision=app_state.revision+1,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING state_key,payload,revision,updated_at',[key,payload,req.user.sub]);await audit(req.user.sub,'state.update',key,{revision:Number(q.rows[0].revision)});const m={type:'state.changed',key,payload:q.rows[0].payload,revision:Number(q.rows[0].revision),updatedAt:q.rows[0].updated_at};broadcast(m);res.json(m)});
app.get('/api/users',auth,role('admin'),async(_q,r)=>r.json((await pool.query('SELECT id,username,role,active,password_changed_at,created_at FROM users ORDER BY username')).rows));app.post('/api/users',auth,role('admin'),async(req,res)=>{const{username,password,role:rr='user'}=req.body||{};if(!username||!password||String(password).length<8)return res.status(400).json({error:'Mindestens 8 Zeichen erforderlich.'});const h=await bcrypt.hash(String(password),12),q=await pool.query('INSERT INTO users(username,password_hash,role) VALUES($1,$2,$3) RETURNING id,username,role,active',[String(username).trim(),h,rr]);await audit(req.user.sub,'user.create','users',{id:q.rows[0].id});res.status(201).json(q.rows[0])});app.patch('/api/users/:id',auth,role('admin'),async(req,res)=>{const sets=[],vals=[];for(const[n,c]of[['username','username'],['role','role'],['active','active']])if(req.body?.[n]!==undefined){vals.push(req.body[n]);sets.push(`${c}=$${vals.length}`)}if(req.body?.password){vals.push(await bcrypt.hash(String(req.body.password),12));sets.push(`password_hash=$${vals.length}`,'password_changed_at=NOW()')}if(!sets.length)return res.status(400).json({error:'Keine Änderung.'});vals.push(req.params.id);const q=await pool.query(`UPDATE users SET ${sets.join(',')},updated_at=NOW() WHERE id=$${vals.length} RETURNING id,username,role,active,password_changed_at`,vals);res.json(q.rows[0]||{})});app.get('/api/audit',auth,role('admin'),async(_q,r)=>r.json((await pool.query('SELECT a.*,u.username FROM audit_log a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 500')).rows));app.use((_q,r)=>r.sendFile(new URL('../public/index.html',import.meta.url).pathname));
const server=http.createServer(app),wss=new WebSocketServer({server,path:'/ws'});broadcast=data=>{const t=JSON.stringify(data);for(const c of wss.clients)if(c.readyState===1)c.send(t)};wss.on('connection',(s,req)=>{try{jwt.verify(new URL(req.url,'http://localhost').searchParams.get('token'),process.env.JWT_SECRET);s.send(JSON.stringify({type:'connected'}))}catch{s.close(1008,'Unauthorized')}});server.listen(Number(process.env.PORT||3000),()=>console.log('Fahrzeugverwaltung Online gestartet'));
